### PR TITLE
fix: do not show warnings when workers >= 10

### LINKED ISSUE #337: Setting workers to >= 10 yields eventemitter warnings
```
root@DESKTOP-5KK9VIR:~/node/node# autocannon -w 10 localhost:3000
Running 10s test @ http://localhost:3000
10 connections
10 workers

⠋ running...(node:9067) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11
 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9067) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error liste
ners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:9067) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close liste
ners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:9067) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish list
eners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
⠦ running...
```

### PR DESCRIPTION
**Pull request by simoneb**
Replaces ora with char-spinner to avoid the warning altogether.

### old explanation

I didn't actually figure out the root cause of why this is happening, and I do realize that making this initialization eager is doing something that's probably unnecessary unless workers are being used. Nevertheless, that's the most reliable way I found to fix this.

The problem seems to come from the bl package used by ora, which does some fancy stream manipulation, eventually leading to the warnings being generated.

Making the initialization of ora eager in the module root makes the issue disappear. 

Closes #337

### CODE REVIEW

File: lib/progressTracker.js [hunk 1]
```diff
@@ -18,6 +18,7 @@ const defaults = {
   renderResultsTable: true,
   renderLatencyTable: false
 }
+const spinner = ora('running...')
```
Comment (mcollina) [inline lib/progressTracker.js:21]: Can you please instantiate this on first use instead?

Comment (simoneb) [reply lib/progressTracker.js:21]: that will reintroduce the problem again :)

Comment (mcollina) [reply lib/progressTracker.js:21]: Keeping it global and instantiating it only on first use should be identical to this.

Comment (simoneb) [reply lib/progressTracker.js]: it is not, see the change I did which delays initialization and see the test I added failing. _when_ it is initialized is what makes the difference and that's also part of the reason why I couldn't quite figure out the root cause

File: lib/progressTracker.js [hunk 2]
```diff
@@ -34,7 +35,6 @@ function track (instance, opts) {
   let durationProgressBar
   let amountProgressBar
   let addedListeners = false
-  let spinner
```
Comment (simoneb) [inline lib/progressTracker.js:37]: even if I move the instantiation here, it will still cause the test failure. moving it outside this method is what fixes it

File: lib/progressTracker.js (hunk 1 above)
Comment (simoneb) [reply lib/progressTracker.js]: ok no wait a second, there's something gnarly at play here. the test is failing with this version of the code on my machine, but it is not failing on CI. looking into that

Comment (simoneb) [reply lib/progressTracker.js]: ok the reason was unrelated. the test file for the progress tracking where I added this test was wrongly named and its tests were never run (I was running that file directly when developing locally, hence I was I saw it failing)

**Comment by salmanm** [comment]
I think the problem starts when Ora tries to mute `process.stdout` stream. And `process.stdout._events.xxx` already contains `n` (number of active workers) listeners. So I appreciate that it's not straightforward.

But why don't we simply get rid of Ora!? I know it's widely used but if it's causing problems, I think it's worth looking for alternatives. `char-spinner` for instance, it's very old and not actively maintained, but I think it works fine and a very simply code base. I'd say we start using it, and if we need to tweak, we can just fork it.

**Comment by simoneb** [comment]
@salmanm fair point. I changed the implementation. rationale was, I'd spent quite some time looking into the issue and the solution seemed good enough. char-spinner is much simpler it turns out so it's a more robust solution indeed. I'd assumed there was some thought put into choosing the spinner library so I didn't consider reverting that decision

**Review by mcollina — APPROVED** [review]
lgtm
